apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5kZWxpbnRlcm5ldC5jb20iOnsidXNlcm5hbWUiOiJrOHMtcHJvZC10b2tlbiIsInBhc3N3b3JkIjoiZ2xkdC1wQUF2M2pnV1FDUDhrd2dvNXR6dCIsImF1dGgiOiJhemh6TFhCeWIyUXRkRzlyWlc0NloyeGtkQzF3UVVGMk0ycG5WMUZEVURocmQyZHZOWFI2ZEE9PSJ9fX0=
